---
kind: pipeline
type: kubernetes
name: kube-services

defaults:
  image: &default_image
    hashicorp/terraform:0.13.5
  env: &default_env
    KUBE_LOAD_CONFIG_FILE: false
    TF_VAR_postgres_admin_password:
      from_secret: postgres_admin_password
    TF_VAR_marta_api_key:
      from_secret: marta_api_key
    TF_VAR_third_rail_twitter_client_id:
      from_secret: third_rail_twitter_client_id
    TF_VAR_third_rail_twitter_client_secret:
      from_secret: third_rail_twitter_client_secret

steps:
- name: plan
  image: *default_image
  environment: *default_env

  commands:
  - terraform init -lock=false -input=false
  - terraform validate
  - terraform plan -lock=false -input=false
  when:
    event: [ push ]
    branch:
      exclude: [ master ]

- name: apply
  image: *default_image
  environment: *default_env

  commands:
  - terraform init -lock=true -lock-timeout=0s -input=false
  - terraform validate
  - terraform plan -lock=true -lock-timeout=0s -input=false -out=tfplan .
  - terraform apply -lock=true -lock-timeout=0s -input=false tfplan
  when:
    branch: [ master ]
